const actionTypes = {
    SET_ANS: 'SET_ANS',
    TOGGLE_HIDE: 'TOGGLE_HIDE',
    TOGGLE_NEXT: 'TOGGLE_NEXT',
    SET_LIVES: 'SET_LIVES',
    REDUCE_LIVES: 'REDUCE_LIVES',
    RESET_SCORE: 'RESET_SCORE',
    INCREMENT_SCORE: 'INCREMENT_SCORE',
    UPDATE_HIGHSCORE: 'UPDATE_HIGHSCORE',
    RESET_INVALID_LETTERS: 'RESET_INVALID_LETTERS',
    UPDATE_INVALID_LETTERS: 'UPDATE_INVALID_LETTERS',
}


export default actionTypes;